### PR TITLE
DM-21186: Rename AuxTel to LATISS

### PR DESCRIPTION
**Pull request by timj**
The defects are associated with the camera and not the telescope.

### CODE REVIEW

**Review by mfisherlevine — COMMENTED** [review]
`latiss` or `LATISS` - I'm not sure. If you are then go ahead and merge 🙂

**Comment by timj** [comment]
Yes. Regarding the name, the problem is that in obs_lsst there is a strong preference to using the lower case name in all files and directory names (or at least camelCase). Unfortunately the defects support code in obs_base has an internal check that the instrument defined in the header of the ecsv files matches the directory name and it doesn't do a case insensitive comparison. I therefore have to use the wrong instrument name in the ECSV file or be inconsistent in the directory naming scheme. Or else I fix obs_base.  @SimonKrughoff how would you feel if we made the directory name comparison case insensitive?

**Comment by timj** [comment]
Actually pipe_tasks now that I look again.

**Comment by timj** [comment]
I made a PR in pipe_tasks which I hope we can accept to clean up this change.

**Comment by mfisherlevine** [comment]
Oh, cool! You will be unsurprised to hear that I don't care very much really though, was just pointing it out in case it was a mistake.

**Comment by mfisherlevine** [comment]
Also - fun fact on a controversial opinion I hold: case should be allowed, but _everything_ should case-insensitive, _all the time_. Not even joking.

**Comment by timj** [comment]
@mfisherlevine that's why you love macOS so much with your case preserving case insensitive file systems...

**Pull request merged**
